#启动端口
server:
  port: 9002
#项目名称
spring:
  application:
    name: order-provider
#eureka配置
eureka:
  instance:
    prefer-ip-address: true #使用服务的id地址注册
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/