server:
  port: 8001
eureka:
  instance:
    # \u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3IP\u5730\u5740
    hostname: localhost
  client:
    # \u662F\u5426\u5411\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
    # \u662F\u5426\u68C0\u7D22\u670D\u52A1
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/